# Generated by Django 4.0.6 on 2022-07-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='drive_link',
            field=models.URLField(null=True),
        ),
    ]
