# Generated by Django 4.0.6 on 2022-08-02 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_information_drive_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='information',
            name='email',
        ),
        migrations.RemoveField(
            model_name='information',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='information',
            name='linkedIn',
        ),
        migrations.RemoveField(
            model_name='information',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='information',
            name='skypeId',
        ),
    ]
